server:
  port: 8084

spring:
  application:
    name: map-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

map:
  google:
    key: "YOU_KEY"